global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the Profiles.Web application
  - job_name: 'profiles-web'
    static_configs:
      - targets: ['app:9090']
    metrics_path: /metrics

  # Scrape the OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics exported by the OTEL collector
  - job_name: 'otel-collector-prometheus'
    static_configs:
      - targets: ['otel-collector:8889']
